---
apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: dst
  name: dst
spec:
  replicas: 1
  selector:
    app: dst
  template:
    metadata:
      labels:
        app: dst
    spec:
      containers:
      - image: bergerx/openshift-udp-test
        imagePullPolicy: Always
        name: dst
        command:
        - socat
        - -v
        - udp-l:8000,fork
        - exec:'/bin/cat'
  triggers:
  - type: ConfigChange
---
apiVersion: v1
kind: Service
metadata:
  name: dst
  labels:
    app: dst
spec:
  ports:
    - protocol: UDP
      port: 8000
      targetPort: 8000
  selector:
    app: dst
  type: ClusterIP

