apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: src
  name: src
spec:
  replicas: 1
  selector:
    app: src
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: src
    spec:
      containers:
      - image: bergerx/openshift-udp-test
        imagePullPolicy: Always
        name: src
        command:
        - bash
        - -c
        - while sleep 1; do echo time:$(date +%F-%T) | nc -q1 -u dst 8000; done
      dnsPolicy: ClusterFirst
      restartPolicy: Always
  triggers:
  - type: ConfigChange
